name: Website Uptime Bot

on:
  schedule:
    - cron: '*/5 * * * *' # Chạy mỗi 5 phút
  workflow_dispatch:      # Cho phép bấm chạy thủ công

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: ambassadors/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pyTelegramBotAPI requests pytz

      - name: Run Bot
        run: python bot.py
